### ISSUE TITLE
Resolving Machine Readable Data

### ISSUE THREAD

**Issue by ewg118** [usc-isi-i2/saam-lod#1]
Machine readable data cannot be resolved from the SAAM LOD framework. Data are not available from either REST URIs or content negotiation.

**Comment by szeke** [comment]
The Smithsonian Museum of American Art took over the endpoint and is deploying the data on their web site. They will make an announcement in the next weeks/months. Apologies for the inconvenience.

**Comment by caknoblock** [comment]
I believe it is available now: http://americanart.si.edu/collections/search/lod/about/
